### ISSUE TITLE
Need transition animations

### ISSUE THREAD

**Issue by Rldeckard** [Rldeckard/tech#1]
Everything is too snappy. Need to add animations to slow it down and add a better user experience

**Comment by TaniaMalhotra** [comment]
Hii, I would like to work on it.
Please guide me through the kind of animations that are to be added.

**Comment by Rldeckard** [comment]
There aren't too many restrictions on the animations here. As stated, the goal is too just to slow it down a little from page to page. Fade in the pages as they come up or fade the main page while adding a scroll affect to the others. Have separate parts fade or swing in in a way of your choosing as they appear on screen.

**Comment by TaniaMalhotra** [comment]
Kindly assign me this issue!
I would start working on it!😀

**Comment by Rldeckard** [comment]
Feel free. Let me know if you have any questions as it's kind of a mess. I'm here to assist with contributions so any and all questions are welcome. If you notice things that need corrected while poking around let me know and I'll create a new issue or toss one in yourself if you have the ability

**Comment by TaniaMalhotra** [comment]
Sure👍

**Comment by HarshaVardhan16** [comment]
Hey,
I would like to work on this. Can you help me understand the working of the project?

**Comment by Rldeckard** [comment]
If you check out the site there is some basic animation already applied by
previous attempts. If you'd like to make further changes, that's perfectly
fine. The goal is soothing the viewer and making it high tech for lack of a
better term. I'm here if you have questions, but basically you clone it and
mostly edit the CSS. The current setup is very tricky so please let me know
if you have any questions!
